# Generated by Django 4.0.8 on 2022-11-01 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=200, null=True, verbose_name='Company Name')),
                ('position', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='notes')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocumentLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Application Id +', to='home.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationProgressLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(0, 'Incomplete'), (1, 'Ready to Apply'), (2, 'Applied')], max_length=50, null=True)),
                ('interviewCall', models.CharField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'Skipped'), (3, 'In Progress')], max_length=50, null=True)),
                ('assessment', models.CharField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'Skipped'), (3, 'In Progress')], max_length=50, null=True)),
                ('interviewFinal', models.CharField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'Skipped'), (3, 'In Progress')], max_length=50, null=True)),
                ('offer', models.BooleanField(null=True)),
                ('accepted', models.BooleanField(null=True)),
                ('applicationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, null=True, verbose_name='Document Name')),
                ('type', models.CharField(choices=[(1, 'Portfolio'), (2, 'Transcript'), (3, 'Resume'), (4, 'Cover Letter'), (5, 'Recommendation Letter'), (6, 'Offer Letter')], max_length=50, null=True)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.AddField(
            model_name='applicationdocumentlink',
            name='coverLetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cover Letter +', to='home.document'),
        ),
        migrations.AddField(
            model_name='applicationdocumentlink',
            name='offerLetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Offer Letter +', to='home.document'),
        ),
        migrations.AddField(
            model_name='applicationdocumentlink',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Portfolio +', to='home.document'),
        ),
        migrations.AddField(
            model_name='applicationdocumentlink',
            name='recommendationLetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Recommendation Letter +', to='home.document'),
        ),
        migrations.AddField(
            model_name='applicationdocumentlink',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Resume +', to='home.document'),
        ),
        migrations.AddField(
            model_name='applicationdocumentlink',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Transcript +', to='home.document'),
        ),
    ]
