# Generated by Django 4.0.8 on 2022-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_application_applicationdocumentlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprogresslink',
            name='assessment',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped'), ('In Progress', 'In Progress')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationprogresslink',
            name='interviewCall',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped'), ('In Progress', 'In Progress')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationprogresslink',
            name='interviewFinal',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped'), ('In Progress', 'In Progress')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationprogresslink',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Ready to Apply', 'Ready to Apply'), ('Applied', 'Applied')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Portfolio', 'Portfolio'), ('Transcript', 'Transcript'), ('Resume', 'Resume'), ('Cover Letter', 'Cover Letter'), ('Recommendation Letter', 'Recommendation Letter'), ('Offer Letter', 'Offer Letter')], max_length=50, null=True),
        ),
    ]
