# Generated by Django 4.0.8 on 2022-11-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_applicationprogresslink_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped'), ('In Progress', 'In Progress')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interviewCall',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped'), ('In Progress', 'In Progress')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interviewFinal',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Skipped', 'Skipped'), ('In Progress', 'In Progress')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Ready to Apply', 'Ready to Apply'), ('Applied', 'Applied')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ApplicationProgressLink',
        ),
    ]
