# Generated by Django 4.0.8 on 2022-11-12 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0008_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='coverLetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cover Letter +', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='offerLetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Offer Letter +', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Portfolio +', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='recommendationLetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Recommendation Letter +', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Transcript +', to='wagtaildocs.document'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
