# Generated by Django 4.0.8 on 2022-11-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0009_alter_application_coverletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Resume +', to='wagtaildocs.document'),
        ),
    ]
